version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: whatsapp-api-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - whatsapp-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: whatsapp-api-backend
    restart: always
    depends_on:
      - mongodb
    ports:
      - "3100:3000"  # Exponiendo el backend en el puerto 3100
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/whatsapp-api?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_PATH=/app/sessions
    volumes:
      - whatsapp-sessions:/app/sessions
    networks:
      - whatsapp-network
      - proxy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: whatsapp-api-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8082:80"  # Exponiendo el frontend en el puerto 8080
    networks:
      - whatsapp-network
      - proxy

networks:
  whatsapp-network:
    driver: bridge
  proxy:
    external: true

volumes:
  mongo-data:
  whatsapp-sessions: