version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: whatsapp-api-mongodb
    restart: always
    environment:
      # Credenciales directas para MongoDB
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: whatsapp_api
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - whatsapp-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: whatsapp-api-backend
    restart: always
    depends_on:
      - mongodb
    ports:
      - "3100:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=ebf8d398c7a6e25ab8c1a72390bd76e8f1a392059d2ec3b3
      - SESSION_PATH=/app/sessions
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/whatsapp_api?authSource=admin
    volumes:
      - whatsapp-sessions:/app/sessions
    networks:
      - whatsapp-network
      - proxy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: whatsapp-api-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8082:80"
    networks:
      - whatsapp-network
      - proxy

networks:
  whatsapp-network:
    driver: bridge
  proxy:
    external: true

volumes:
  mongo-data:
  whatsapp-sessions: