version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: whatsapp-api-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: whatsapp_user
      MONGO_INITDB_ROOT_PASSWORD: strong_password_here
      MONGO_INITDB_DATABASE: whatsapp_api
    ports:
      - "161.35.232.210:27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - whatsapp-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: whatsapp-api-backend
    restart: always
    depends_on:
      - mongodb
    ports:
      - "161.35.232.210:3100:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=your_strong_jwt_secret_key_here
      - SESSION_PATH=/app/sessions
      - MONGODB_URI=mongodb://whatsapp_user:strong_password_here@mongodb:27017/whatsapp_api?authSource=admin
    volumes:
      - whatsapp-sessions:/app/sessions
    networks:
      - whatsapp-network
      - proxy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: whatsapp-api-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "161.35.232.210:8082:80"
    networks:
      - whatsapp-network
      - proxy

networks:
  whatsapp-network:
    driver: bridge
  proxy:
    external: true

volumes:
  mongo-data:
  whatsapp-sessions: